org: mohuk
app: fps-connect-notifications
service: fps-connect-notifications

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverless-fps-connect-agent

functions:
  index:
    handler: index.handler
    environment: 
      FPS_PARENT_CREDENTIALS: ${file(./credentials.json):cookie}
